///////////////////////////////////////////////////////////////////////////
// Description: Data Access class for the table 'KhoNPL_tbNhapKho'
// Generated by LLBLGen v1.3.5996.26197 Final on: Friday, March 19, 2021, 3:08:26 PM
// Because the Base Class already implements IDispose, this class doesn't.
///////////////////////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace CtyTinLuong
{
	/// <summary>
	/// Purpose: Data Access class for the table 'KhoNPL_tbNhapKho'.
	/// </summary>
	public partial class clsKhoNPL_tbNhapKho : clsDBInteractionBase
	{
     
        
	}
}
