///////////////////////////////////////////////////////////////////////////
// Description: Data Access class for the table 'HUU_LenhSanXuat_ChiTietLenhSanXuat_ToGapDan'
// Generated by LLBLGen v1.3.5996.26197 Final on: Thursday, March 4, 2021, 4:22:31 PM
// Because the Base Class already implements IDispose, this class doesn't.
///////////////////////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace CtyTinLuong
{
	/// <summary>
	/// Purpose: Data Access class for the table 'HUU_LenhSanXuat_ChiTietLenhSanXuat_ToGapDan'.
	/// </summary>
	public partial class clsHUU_LenhSanXuat_ChiTietLenhSanXuat_ToGapDan : clsDBInteractionBase
	{
        //pr_HUU_LenhSanXuat_ChiTietLenhSanXuat_ToGapDan_SelectAll_XuatkhoNPL
        public DataTable SelectAll_GuiDuLieuBangTrue()
        {
            SqlCommand scmCmdToExecute = new SqlCommand();
            scmCmdToExecute.CommandText = "dbo.[pr_HUU_LenhSanXuat_ChiTietLenhSanXuat_ToGapDan_SelectAll_GuiDuLieuBangTrue]";
            scmCmdToExecute.CommandType = CommandType.StoredProcedure;
            DataTable dtToReturn = new DataTable("pr_HUU_LenhSanXuat_ChiTietLenhSanXuat_ToGapDan_SelectAll_GuiDuLieuBangTrue");
            SqlDataAdapter sdaAdapter = new SqlDataAdapter(scmCmdToExecute);

            // Use base class' connection object
            scmCmdToExecute.Connection = m_scoMainConnection;

            try
            {
                m_scoMainConnection.Open();

                //scmCmdToExecute.Parameters.Add(new SqlParameter("@iID_LenhSanXuat", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, m_iID_LenhSanXuat));
                sdaAdapter.Fill(dtToReturn);
                return dtToReturn;
            }
            catch (Exception ex)
            {
                // some error occured. Bubble it to caller and encapsulate Exception object
                throw new Exception("pr_HUU_LenhSanXuat_ChiTietLenhSanXuat_ToGapDan_SelectAll_GuiDuLieuBangTrue", ex);
            }
            finally
            {
                //Close connection.
                m_scoMainConnection.Close();
                scmCmdToExecute.Dispose();
                sdaAdapter.Dispose();
            }
        }
        public DataTable SelectAll_w_iID_LenhSanXuat()
        {
            SqlCommand scmCmdToExecute = new SqlCommand();
            scmCmdToExecute.CommandText = "dbo.[pr_HUU_LenhSanXuat_ChiTietLenhSanXuat_ToGapDan_SelectAll_W_iID_LenhSanXuat]";
            scmCmdToExecute.CommandType = CommandType.StoredProcedure;
            DataTable dtToReturn = new DataTable("pr_HUU_LenhSanXuat_ChiTietLenhSanXuat_ToGapDan_SelectAll_W_iID_LenhSanXuat");
            SqlDataAdapter sdaAdapter = new SqlDataAdapter(scmCmdToExecute);

            // Use base class' connection object
            scmCmdToExecute.Connection = m_scoMainConnection;

            try
            {
                m_scoMainConnection.Open();

                scmCmdToExecute.Parameters.Add(new SqlParameter("@iID_LenhSanXuat", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, m_iID_LenhSanXuat));
                sdaAdapter.Fill(dtToReturn);
                return dtToReturn;
            }
            catch (Exception ex)
            {
                // some error occured. Bubble it to caller and encapsulate Exception object
                throw new Exception("pr_HUU_LenhSanXuat_ChiTietLenhSanXuat_ToGapDan_SelectAll_W_iID_LenhSanXuat", ex);
            }
            finally
            {
                //Close connection.
                m_scoMainConnection.Close();
                scmCmdToExecute.Dispose();
                sdaAdapter.Dispose();
            }
        }
    }
}
